### ISSUE TITLE
Googlebot

### ISSUE THREAD

**Issue by tmshv** [RisingStack/koa-prerender#10]
Why there is no mention about Googlebot (and Yandex) in crawlerUserAgents?

**Comment by thoop** [comment]
Googlebot and Yandex support the escaped fragment protocol so they don't need to be matched by user agent in order to be supported. If you are using html5 push state, just add `<meta name="fragment" content="!">` to the head of your page and they will crawl URLs with the ?_escaped_fragment_= parameter.

**Comment by tmshv** [comment]
Thanks. Yes, I already find it in Google documentation.

It is not working first time for me so I decided to force matching Googlebot using User Agent field.

**Comment by thoop** [comment]
@tmshv I would suggest not matching the Googlebot user agent to prevent being penalized for cloaking. I'm happy to help make sure you have the escaped fragment protocol set up correctly in order to prevent any issues. Let me know how I can help!
